// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6oSnv8_0hjZhTfW-6tZ3EK0oVhsTqyAY',
    appId: '1:246474481860:web:3be5532fda94c6ec18a991',
    messagingSenderId: '246474481860',
    projectId: 'acesso-firebase-b5589',
    authDomain: 'acesso-firebase-b5589.firebaseapp.com',
    storageBucket: 'acesso-firebase-b5589.appspot.com',
    measurementId: 'G-PPGEE09ZLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwEhDdCsBS6_IzA_NM3RKvKbpBzyCCOQU',
    appId: '1:246474481860:android:0670f99925bafe1418a991',
    messagingSenderId: '246474481860',
    projectId: 'acesso-firebase-b5589',
    storageBucket: 'acesso-firebase-b5589.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrAHyDs9YxxlWyTTBDcmUefMI0m5280dw',
    appId: '1:246474481860:ios:23aa72f7f481f33518a991',
    messagingSenderId: '246474481860',
    projectId: 'acesso-firebase-b5589',
    storageBucket: 'acesso-firebase-b5589.appspot.com',
    iosBundleId: 'com.example.patinhaPerdida',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrAHyDs9YxxlWyTTBDcmUefMI0m5280dw',
    appId: '1:246474481860:ios:2eff243f1155726c18a991',
    messagingSenderId: '246474481860',
    projectId: 'acesso-firebase-b5589',
    storageBucket: 'acesso-firebase-b5589.appspot.com',
    iosBundleId: 'com.example.patinhaPerdida.RunnerTests',
  );
}
